7442
CSCD01/team_22-project pull request #25
Opened 2020-03-20 19:19 UTC by hesidi

2020-03-21 21:02 UTC, agojiya commented on doc/deliverable3/7442.md
> +This PDF viwer doesn't have the ability to highlight multiple search terms and phrases which is available to use before in [#5496](https://github.com/mozilla/pdf.js/pull/5496). The feature is about t
Typo in the word 'viewer'

2020-03-21 21:04 UTC, agojiya commented on doc/deliverable3/7442.md
> +We are wxcepting to make the multiple search feature working when usrs open pdf file in viewer. This could be tested by giving a query string in an array (#search = ["p1", "p2", "w1"]) and take a loo
Typo in words 'expecting', 'users', 'viewer', and 'highlight'

2020-03-21 21:07 UTC, agojiya requested changes
Typos in the document

2020-03-21 21:19 UTC, agojiya approved these changes

2020-03-22 19:37 UTC, huang325 approved these changes

2020-03-22 23:22 UTC, merged